service: undefeated-scraper

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  stage: dev
  environment:
    DYNAMODB_TABLE: sneakerwave-products
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  include:
    - utils/**

functions:
  scrape:
    handler: handler.scrape
